services:
  mongo:
      image: mongo
      container_name: mongo_container
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: company
        MONGO_INITDB_ROOT_PASSWORD: myservices
        MONGO_INITDB_ROOT_DATABASE: companies
      ports:
        - 27017:27017
      volumes:
        - mongo_data_container:/data/db
volumes:
  mongo_data_container: