services:
  mongo:
      image: mongo
      container_name: mongo_container
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: ${ONGODB_USENAME}
        MONGO_INITDB_ROOT_PASSWORD: ${ONGODB_PASSWORD}
        MONGO_INITDB_ROOT_DATABASE: ${ONGODB_DATABASE}
      ports:
        - 27017:27017
      volumes:
        - mongo_data_container:/data/db
volumes:
  mongo_data_container:

     = 'companies'
    = 'company'
    = 'myservices'