services:
  mysql:
    container_name: mysql_container
    restart: always
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Myservername
      MYSQL_DATABASE: manufacturing
    cap_add:
      - SYS_NICE
    ports:
      - 8080:8080
    volumes:
      - "./dumps/schema.sql:/docker-entrypoint-initdb.d/1.sql"
