services:
  db:
    container_name: mysql_container
    restart: always
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: PASSWORD
      MYSQL_DATABASE: DATABASES
    cap_add:
      - SYS_NICE
    ports:
      - 8080:8080
    volumes:
      - mysql_data_container:/var/lib/db
volumes:
  mysql_data_container:
