services:
  mysql:
    container_name: mysql_container
    restart: always
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Myservername
      MYSQL_DATABASE: manufacturing
    cap_add:
      - SYS_NICE
    ports:
      - 8080:8080

  mongo:
      image: mongo
      container_name: mongo_container
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: company
        MONGO_INITDB_ROOT_PASSWORD: myservices
        MONGO_INITDB_ROOT_DATABASE: companies
      ports:
        - 27017:27017
