
INSERT INTO  products (product_name, product_number, product_vendor, product_description, quantityin_stock, buy_price, resellers_reseller_id) VALUES
('Shrimp - Prawn', 43, 'Schneider-Marvin', 'potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus', 32, 137.13, 1),
('Daves Island Stinger', 80, 'Tromp-Schuster', 'orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum', 48, 133.39, 2),
('Pork - Bacon Cooked Slcd', 89, 'Rolfson, Mills and Mitchell', 'convallis nulla neque libero convallis eget eleifend luctus ultricies eu', 31, 180.42, 3),
('Lamb - Leg, Bone In', 54, 'Hermiston Group', 'vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum', 36, 100.31, 4),
('Vegetable - Base', 82, 'Gorczany Inc', 'nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin', 31, 154.66, 5),
('Soup - Campbells - Chicken Noodle', 98, 'Anderson and Sons', 'duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus', 50, 160.09, 6),
('Momiji Oroshi Chili Sauce', 27, 'Gottlieb, Ernser and Romaguera', 'nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit', 17, 107.04, 7),
('Appetizer - Spring Roll, Veg', 29, 'Koelpin, Grimes and Reilly', 'enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in', 45, 149.87, 8),
('Bar Special K', 100, 'Hyatt-Kihn', 'sollicitudin ut suscipit a feugiat et eros vestibulum ac est', 10, 175.17, 9),
('Wine - Red, Gallo, Merlot', 89, 'Prohaska Inc', 'nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta', 45, 138.61, 10),
('Wine - Fino Tio Pepe Gonzalez', 30, 'Gibson-Mann', 'imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing', 22, 136.68, 11),
('Sugar - Crumb', 56, 'Leannon Group', 'phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in', 6, 125.59, 12),
('Napkin - Cocktail,beige 2 - Ply', 57, 'Kemmer Group', 'facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget', 26, 173.53, 13),
('Potatoes - Yukon Gold, 80 Ct', 22, 'Kerluke LLC', 'lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus', 32, 167.97, 14),
('Edible Flower - Mixed', 67, 'Prosacco, Monahan and Gaylord', 'eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem', 38, 130.47, 15),
('Oil - Avocado', 36, 'Auer, Kozey and Schultz', 'ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam', 16, 186.98, 16),
('Transfer Sheets', 45, 'Hettinger LLC', 'viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis', 47, 184.12, 17),
('Mayonnaise - Individual Pkg', 16, 'Pollich Group', 'feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst', 13, 157.57, 18),
('Glycerine', 43, 'Windler, Schiller and Wehner', 'vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra', 33, 100.74, 19),
('Bread - Rolls, Rye', 36, 'Cole, Daugherty and Reilly', 'tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim', 10, 108.04, 20),
('Sauce - White, Mix', 69, 'Cormier, Hyatt and Bins', 'quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie', 44, 110.24, 21),
('Muffin Batt - Ban Dream Zero', 28, 'Dibbert, Dooley and Flatley', 'ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae', 7, 196.96, 22),
('Smoked Tongue', 17, 'Kassulke-Hilpert', 'ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante', 37, 150.86, 23),
('Bandage - Flexible Neon', 70, 'Carter-Glover', 'luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat', 44, 156.4, 24),
('Ham - Smoked, Bone - In', 97, 'Effertz Group', 'enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae', 50, 112.61, 25),
('Beef - Tongue, Fresh', 8, 'Welch Inc', 'et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque', 31, 169.69, 26),
('Taro Leaves', 28, 'O''Keefe, Schmidt and Simonis', 'sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo', 1, 131.29, 27),
('Ecolab Silver Fusion', 47, 'Quitzon, Wuckert and Bogan', 'nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse', 13, 152.14, 28),
('Parsnip', 87, 'Pacocha-Rogahn', 'cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus', 41, 121.44, 29),
('Onions - Dried, Chopped', 74, 'Kovacek, Walsh and Schmidt', 'ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et', 35, 148.81, 30),
('Wine - Vovray Sec Domaine Huet', 7, 'Wolff and Sons', 'consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in', 39, 106.3, 31),
('Rice - Brown', 84, 'Schneider-Reilly', 'neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac', 16, 193.1, 32),
('Cake - Dulce De Leche', 26, 'Thompson, Torphy and Jacobi', 'augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac', 8, 131.71, 33),
('Vegetable - Base', 35, 'Kuhic Group', 'vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit', 43, 118.09, 34),
('Pasta - Elbows, Macaroni, Dry', 8, 'Bayer LLC', 'convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia', 16, 125.75, 35),
('Cheese Cloth No 100', 24, 'Barton and Sons', 'in libero ut massa volutpat convallis morbi odio odio elementum', 29, 182.93, 36),
('Soup - Campbells Tomato Ravioli', 96, 'Frami Group', 'magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci', 12, 195.24, 37),
('Grand Marnier', 11, 'Parisian, Borer and Considine', 'nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at', 12, 127.56, 38),
('Sauce - Vodka Blush', 39, 'Schamberger-Aufderhar', 'tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl', 46, 197.44, 39),
('Kellogs Raisan Bran Bars', 8, 'Mante, Hoeger and Howe', 'posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel', 43, 120.13, 40),
('Pasta - Bauletti, Chicken White', 48, 'Rath-Labadie', 'venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo', 34, 190.45, 41),
('Table Cloth 62x114 Colour', 12, 'Denesik Inc', 'dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus', 28, 141.98, 42),
('Sauce - Salsa', 42, 'Gleason, Will and Maggio', 'eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer', 21, 102.15, 43),
('Ecolab - Balanced Fusion', 33, 'Moen Inc', 'suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum', 28, 183.23, 44),
('Gloves - Goldtouch Disposable', 72, 'Pouros, Frami and Leuschke', 'rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem', 5, 177.16, 45),
('Mix - Cocktail Strawberry Daiquiri', 93, 'Schmidt and Sons', 'consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent', 45, 174.02, 46),
('Sobe - Lizard Fuel', 99, 'Stamm-Marvin', 'eget congue eget semper rutrum nulla nunc purus phasellus in felis', 11, 146.02, 47),
('Soup - Campbells, Minestrone', 40, 'Rice-Harvey', 'imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum', 46, 192.95, 48),
('Cheese - Brie Roitelet', 73, 'Nicolas and Sons', 'etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean', 26, 140.73, 49),
('Rum - Light, Captain Morgan', 22, 'Bogisich Group', 'praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede', 14, 118.14, 50);